language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then NTESTER_FLAGS="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; else NTESTER_FLAGS="-p php"; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php coveralls.phar --verbose --config tests/.coveralls.yml
    || true;
    fi

after_failure:
  # Print *.log content
  - cat ./tests/temp/exception.log;

script:
  - ./tests/run-tests $NTESTER_FLAGS ./tests/src
  - php ./tests/src/UploadTest.phpt
